### ISSUE TITLE
Some questions about the human evaluation 

### ISSUE THREAD

**Issue by drxmy** [meetdavidwan/factpegasus#1]
Really interesting work. 

But i am not sure that i understand the human evaluation method. In my understanding, each result has 3 workers who will give 0/1 for factuality. Then their average will be the final score for this result. The 39.66 of FACTPEGASUS is sum of all 100 scores.

Do i understand correctly?

**Comment by meetdavidwan** [comment]
Hi sorry for the late reply. Yes your understanding of it is correct. Let me know if you have any other questions!

**Comment by drxmy** [comment]
Thank you!
